language: node_js
node_js:
- node
env:
script:
- yarn test
- yarn run build
deploy:
  provider: heroku
  app: tognox
  api_key:
    secure: MyP6Dq4MVTcB9hgH+CdqQ09sXiTVuZelZXyriKAApsPklJWGKn0mJUCKCMQpAwDOL+sLpq9zZOU5ZP0kn6/2jO903G1eYmduUyF791R1uQ7/bFJmKkeRT/fWkLmP9JJCE53yCkjRVnPOvB4aLwTVNO+gYbLnO2TCL0PSpYBkE1SaSYarCMGAHBVkcIW9/lq/xh7o9+JF0NnHJTGLXsusxkkHmWLPHves0WL3Z+ip+UjCM/v5J83dc61jah7aJ0u795ktB36Evb47UBiieXmMxG9ygotLvb4y9CsWfF5wz93NW+OXLz8VTsre92aK0CebzZmHe74hm6R1O2mYZeKxB19cY/5Ak1vYLxclm7vPed+N/Qv8tU5PXsyOHfxSfToYJnUw3fgK8C34LEsPIf4IbQzhVwbzuVfVgiK7lU8O/alQvfligSmM9A4MHpVdzjK61YbU7flt0RiH9wKjln2AuYFs2hHXWWda7tueoYLR4S4MQLI2lBWB4gj4O16Ez3sDbYXVWjcPD+/I6yxQv1Rjmk13cF5YBmi3TfAI7Nk6QGzb/IzaYQyr44wYWKAQ079BkcnfJ6rhC/YZ1/F7jZPk+D8Ec9uB5h232Q8zHUTybyxZAYDHSHQ/BSyKh7MftIcRRxKyRHrb9h81D2KVidQ92ADIgaHN1XaDGwzQ2XIk5oA=
  skip_cleanup: true
  on:
    branch: ci-setup
