language: node_js
node_js:
- node
script:
- yarn test
- yarn run build
deploy:
  provider: heroku
  app: tognox
  api_key:
    secure: IgmdDqmS0a//Y/RWn/xN/PMo9Ns9iQJuUeA1Yd0i/lwiOIuLcr240QO7I/kHC93jiNpXV7BLtjcsZGGkHAGS2rwQmLSadx2h9GkDKUXUQbV0foEM58SKORRFtmomTz++asCNUFfVnAlC+QLBoTHO20fDYovkF/7hiUsUCq88wKRTnAKiK1LSKDlyFF2cA//WSTW90H+1iCcl01SvWOhEmotPtls2ddJdz70Ec17ORSgqqHS8Y8v2oc+pUged9rmsUcaPxyxq0cx8mxSpSyW72qzh4E2e8+ZK7Qq+t3tM+KnCq0EjrdAZeKCzWwMJnIiYkEkvoan2semcMU+94RWlVepnVVGiYAkHM8fCUhe5u/ryLpifUlBUdAr1d28umDeqmaq9SVWxw+82OZoN6jfPUyPPT+3RT9lCM20oXpICN0+fpaGS3yjJ+zslRmJKqmlmtpw2NJ8cfV9mceY8T6SdxnW5aRGnQHXqG2EESr4ZbwvIL3zddPxvW0FZKtmnm6oZhbai8hjllS4+ruCtFc1naJB2eI0tpaogkHZSho77WL0fEoHFAwPR7ACkUuI8BumoixQlsGTmMdCalwvVnP/23/zBWpqkJy71zukjkfgO1s/rrUpoHPgHNzcNiHlh7z93DdJ8QZ7t9c81aGlYUGkFmvWYpkuO4WvkExlNl7zWPIw=
  skip_cleanup: true
  on:
    branch: ci-setup
