language: node_js
node_js:
  - node
env:
  global:
  - SFTP_USER="travis-ci@andytonini.com"
  - SFTP_PASSWORD=[password]
script:
  - yarn test
  - yarn run build
after_success:
  - ./scripts/deploy.sh
