language: node_js
node_js:
  - node
env:
  global:
    - SFTP_USER="travis-ci@andytonini.com"
    - SFTP_PASSWORD=[password]
    - secure: mobRkuoPUgFjBumxdAfIMb96n0DiqonsUKfKlPgZrwYssNzsaZiL+/tw+cwoMn0nO+2QkVBoagKy77VTQR9mutlK1FX3bk8bZblzdBlG0nFIPCbpjr+RCd4cj2LP64VPAWFiTVPE6Sonnkk9u5rNre9Ef4f9loFnntRnd5tg1ZYcL6C8JgZXQxBWd/nGwoWHj/hEsXf+5O/IihoDyrK1bB96R+4JZW4M6/uDVNH4Oo3llXcnlGgLJCWpMgRiiCVbVwU/TMFCgCq1GOrBUMJoG/LACtTIU5nfUcaNEvry/JgWO4oEBuZokAizc3VKlYryZlVni8R0aUPLsy+jvBNpAY4iV1XMbpw/GByZ5EqXDxJUjxPRhGkbFPDstvIiSbsDdQ0LnH5vvAwgRUbpDtaSvfBpEmL+kNPSfZJiapfqBn41nofXXS+By45q73QKf33kyaouWoeHHDT9DmX1DD23gnC6MeRzka7o8S3kyAOuu4I3cptMMm+WsUIooE2lZRqDZ9pVDXUx3rkY+LyHTwRUL7M5qvUXWfP6K+zQP4yVdfqlo6sjGxIIiBkbX0X6oY5kdeBMX8x6WDSqGJ1EG1Jk8wwHLJAock9It+UC+Zv/TcV9oSpSrdmPAziGEPqgWoOSemdt49CCDQxeGC36riJGe0CaIchUcVHoYiFiJpHd3eY=
script:
  - yarn test
  - yarn run build
deploy:
  provider: heroku
  app: tognox
  api_key:
    secure: "DZ6p7fGpksFWJam5RBIcz1rcH1pye/x3rmv6dC7gokWO+Cr7+Mh6b3Y8OP+N5rCwGcLhCQ/h8oXjoxholdvP6atT3Ui2cun5W8qOfly6ttqqOkTK9mfLTIbSeZbBtLpge2xvQ5SCQB5dbBMKuKWWwJTcUDoxc25eU2DIXFf7XtvqrKnobHOoNq4fNNh+BN2x1kZNVNv4smlXblP/23kvs+yGZd40n5MK7TLbgu4uJMvxWrM9uOc5BKaYiTAIly+IhyKAd0VHDuwRtRfrUa96ReYd2iRIOPkFoMi4DOdnCXodjm/o7esR8VL88eg05m7GSvXh03PFyG+zon3m+GwKYQHiR973XC14SRT5PrbQWDXUhphT/gzPNH6q2bLv8kjnyQSfkAu+JKkpbpJNSe6GvPoEh5vBzyuuUFEWPFPH6LaOJGHID10ypINi9ah9s0Tcr8SQ/CdQB1hl9GVVL9VyUfWQZn2g4/aE+6WKDmmn1mzks4Sb5s/T339Avhya+6rgTUw3CkhocTq8JRi7MPCZaEYIdcPMWHthHPBZGIHGh3J48yxvaTAqDVr7UB0w8SRlb2zbOS7xerHhMjXhZUL9c9hikKhjLRAoIeZ7hQjQiZF7Qjvvj/SMsuqaJ1rFilXzUCxcaPeeP+c6qp/QYF0dmbKc+RFZpkRWt+gGlf8IQUs="
  skip_cleanup: true
  on:
    branch: ci-setup
