language: node_js
node_js:
- node
env:
  global:
  - SFTP_USER="travis-ci@andytonini.com"
  - SFTP_PASSWORD=[password]
  - secure: mobRkuoPUgFjBumxdAfIMb96n0DiqonsUKfKlPgZrwYssNzsaZiL+/tw+cwoMn0nO+2QkVBoagKy77VTQR9mutlK1FX3bk8bZblzdBlG0nFIPCbpjr+RCd4cj2LP64VPAWFiTVPE6Sonnkk9u5rNre9Ef4f9loFnntRnd5tg1ZYcL6C8JgZXQxBWd/nGwoWHj/hEsXf+5O/IihoDyrK1bB96R+4JZW4M6/uDVNH4Oo3llXcnlGgLJCWpMgRiiCVbVwU/TMFCgCq1GOrBUMJoG/LACtTIU5nfUcaNEvry/JgWO4oEBuZokAizc3VKlYryZlVni8R0aUPLsy+jvBNpAY4iV1XMbpw/GByZ5EqXDxJUjxPRhGkbFPDstvIiSbsDdQ0LnH5vvAwgRUbpDtaSvfBpEmL+kNPSfZJiapfqBn41nofXXS+By45q73QKf33kyaouWoeHHDT9DmX1DD23gnC6MeRzka7o8S3kyAOuu4I3cptMMm+WsUIooE2lZRqDZ9pVDXUx3rkY+LyHTwRUL7M5qvUXWfP6K+zQP4yVdfqlo6sjGxIIiBkbX0X6oY5kdeBMX8x6WDSqGJ1EG1Jk8wwHLJAock9It+UC+Zv/TcV9oSpSrdmPAziGEPqgWoOSemdt49CCDQxeGC36riJGe0CaIchUcVHoYiFiJpHd3eY=
script:
- yarn test
- yarn run build
deploy:
  provider: heroku
  app: tognox
  api_key:
    secure: U8325wQJ9PJUp5UbqraCqARVFba5XFW0dZa0vJXCpjGsXK2KP2Fqa/vsHMVoIVkfUFUdEbxDEjHuxCrB5BxGf8j9lIkqq7Qr/K58mizfiV4fzxQZnRViZJ/gOlUKKXLMabAW3L2MiDgZxG19D7EFAXUeubL04OkZEl5okMOwtXJXI0NMp1h117rAuBAwsh0Ley+vp3BHMniSalAKovD73hmWJowsKkKjyTlCy+YKZSAKpzaFxwWPEfYVys2W67LzsrBQFTqmJhnXDcEHoIwcUK3Y5WzsDopihH/zdZZh2YZLyGzwO2NLcmhIEJMdxc0KUgkV+9WbSl/xCsbd4ZKiNqNKjTjchUyPlczRlVD5hGbb/dEE0qTmZ+gmzhKMKut1Fbjy4aCKc3G4P5S6Y3zP/bz65vnbFJSyGVzyVFuiGiLIFEFk1CwjoEVjJdfxJnJ9gOCHDHj1bYB7FOcENaVsaD9tYx5D9wxN5f7Zvmzo3dk6850ofhq1Ss66eubNd61dgTpmIEnmSt/9nNtNG3nAUrZBvqFcnmlGa7NNmxY5MxQIfmNLih2962/0ANWTeOwIXQVP8VIbzMtvZlUF9T4e6mfy5qhV6n0+evfDGIUKi1vbk4EI+akEqxyLzrjVqEHdhMLgyBhNic0Ld2q0rtk/1utEnCvJppbWd4ThGbAWBDw=
  skip_cleanup: true
  on:
    branch: ci-setup
