language: node_js
node_js:
- node
env:
  global:
  - SFTP_USER="travis-ci@andytonini.com"
  - SFTP_PASSWORD=[password]
  - secure: mobRkuoPUgFjBumxdAfIMb96n0DiqonsUKfKlPgZrwYssNzsaZiL+/tw+cwoMn0nO+2QkVBoagKy77VTQR9mutlK1FX3bk8bZblzdBlG0nFIPCbpjr+RCd4cj2LP64VPAWFiTVPE6Sonnkk9u5rNre9Ef4f9loFnntRnd5tg1ZYcL6C8JgZXQxBWd/nGwoWHj/hEsXf+5O/IihoDyrK1bB96R+4JZW4M6/uDVNH4Oo3llXcnlGgLJCWpMgRiiCVbVwU/TMFCgCq1GOrBUMJoG/LACtTIU5nfUcaNEvry/JgWO4oEBuZokAizc3VKlYryZlVni8R0aUPLsy+jvBNpAY4iV1XMbpw/GByZ5EqXDxJUjxPRhGkbFPDstvIiSbsDdQ0LnH5vvAwgRUbpDtaSvfBpEmL+kNPSfZJiapfqBn41nofXXS+By45q73QKf33kyaouWoeHHDT9DmX1DD23gnC6MeRzka7o8S3kyAOuu4I3cptMMm+WsUIooE2lZRqDZ9pVDXUx3rkY+LyHTwRUL7M5qvUXWfP6K+zQP4yVdfqlo6sjGxIIiBkbX0X6oY5kdeBMX8x6WDSqGJ1EG1Jk8wwHLJAock9It+UC+Zv/TcV9oSpSrdmPAziGEPqgWoOSemdt49CCDQxeGC36riJGe0CaIchUcVHoYiFiJpHd3eY=
script:
- yarn test
- yarn run build
deploy:
  provider: heroku
  app: tognox
  api_key:
    secure: H2jBpR1WY8x5RtoB9AZg9Sb28rsulANqU+UNYoC4ud87zaevU2cSu04FwKdlWmlTfBzc7OXayjsd5tYcWCEZESZODs3YaM6NtbXrWXrN45te+Jp7H15PNU7sb0miC0hamv3fKIAFJ/VTY8ZNh1pefLNRjK0vp0ihRg5fdOGWXgvAh02eaXnFKJBPY5uJ9/rvxConssqYJSWc7aU0oCgbq4iMLxjfVIjPbUy4/soCBhzcr2YXgxhehexsyfnEXcAhiEguSVAv60X2SzJ21YfabJo1iwwabbzn3Io0W1moXKHHmp1LVm6XUl/I+iTeyfNpfndXG9DUllxK/kjZ2rL7ULtCsWj32zkQtHFUEEvIEZNtSJGlGlsydM1eAOJ8TRBOqOuUR8XyxpvUu8CiMh617ee4DFm8ekax2XCBx+X1tYHRUnQN2QUCybJJKRlPKbkWaOzpdeSlC1LcmN1nzfyM3iarD0EJ1h+GTkf/vqCdD8fuBR6S7eiyOURY3cubmnBcq6Xn1JeeFAwuupFPe2/NDVQDWw2rORN54YU8DTe1aB0KLPOoUit45yJNbwkPDhYEWRAVe2qdk1aEiken2Iddo6D8C3OiQXJ4qwPHPqQ891EP3em3zLjqU7R31L8BE5qOt6UkmhBDmJb+cs1jMVf7FH6GeQqB4/gQa1OrqYt10Ic=
  skip_cleanup: true
  on:
    branch: ci-setup
