language: node_js
node_js:
- node
script:
- yarn test
- yarn run build
deploy:
  provider: heroku
  app: tognox
  api_key:
    secure: HX/7fhkJbr9GlgoYcoOgOh0KC3BTaCV12/a1+j5KUxK2RQV6jSgiYc7U8lKzGLfR2c+oQAHod7S1MJ6wgPO0STu6okf1olB45eEX0/yhCtgUj5HNQ48Ymvh08IcPfV/0xMKXEFasEIqQznRbX/PWaXRbfGj0v12zPXbWstSf8P6xfFLECmADSRXvlXdUL5/r90ol7JqUlelNO+bwMiNMP2d1FwI2yLwSAW0QVeDCP/+/a9G/xJV79gaBC/dgDkoU43ryIUbc24w22bfcqDDkYrMbDztWWQ/zZnc3w5AlX+Pp72D2V7/BfXGJiEWYWhqMKav3EyuZYxW+Mm+0q9CWvTMtmYVC5lO++2o7r74zzNCEWbwwV9ViGFwEE46ig76kv+5pvLkN7NdrATDc3IEYJwiehJ3AqSzm/LaZ3AVA/rbhg0D61hySACy0tS+d6gh68td5XPkMrQ42cTJWZ4IkmCPJ1h632F8o+p+ezn3dJ32qOkoOzcE/KVCBrn1TFjNkgGkAi+IPsmVJi1A9meKKPGSSwqnz4n+K9VciqFSnVJRK7wrvoMSs86/MhyvRBJkapGcFcSb/GI3bEai0k827zhicyzduj+5IjllwtRamexbiT1P2q1FKp8wr6bdujWWn6/btJMMQhz8iNjoUF4wnQJCYrCvpMo1v2aYe3sIgZY8=
  skip_cleanup: true
  on:
    branch: ci-setup
