language: node_js
node_js:
- node
script:
- yarn test
- yarn run build
deploy:
  provider: heroku
  app: tognox
  api_key:
    secure: "pyjgK7V9THlogVhx0XYZYiWFYmJ0TKTW8ZRZyEGb7q7kycwQ5VKcjtNL9LzWNHJrghBfi1sJ6t5xQjhumfcjEPlWkecRyD+SefhglH6fVzMU3AzX5j+lCvNODKnehpWxsjK7/yJIlzHPbJxgj9LGpMqLlot13fOmxblE5049l7vJotQm/Gk5Twc3U67AlQ478xh8yDxHrKpvfqD0Z1wltPZxTkO9inK7kLI+Pz8w85KcwcOsxRbdrqAzdtnkgrAc0b1GYafksQSyYfxvgNcQ3fwTkIogVBwXzzJVjE3oqI8CR59iJ1I6zQA4RNxTWebaWmY9Dc66AEi4UAW658BEJ/7xV0xW9xAsaeMoLeP6NXtusyuFlPEJY2uOW60g0Xy1E90iPY1GeDdxJr8f8zYTRa3Cuv3DBFy27ZbQDN1Sfd0OMmLOsvQ4PsaWc3hBavek7ZPFuafJmaKXqGr9I8NITyxlUH+hxsKOL/H2ALLLkDbM9tUgZub5Cq2wVhj0G92Kc8mmikNsV21XH5lN0X+uhRnRU3wpDkqalUqYuW05sVdlLOLfDmUSrochoX4xQOjbayvdZjON0X9K8dyVDUiXTcl+KagVt01hlMYO9+y38ksjZii2Aiw2rnja3FCb9+gPr3I9Ik754JR79wRBpoItQmExk3sLKM9ckTOpwEnD4aI="
  skip_cleanup: true
  on:
    branch: ci-setup
